dataset:
  uri: "csv://src/test/resources/data.csv"
  metricColumns:
    - "usage"
  labelColumn: "is_anomaly"

classifiers:
- id: "percentile"
  parameters:
    cutoff: 1.0
    includeHi: true
    includeLo: true
